config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  namespace :dashboard do
    resources :cars, expect: %i[show]
    resources :users, expect: %i[show]
  end

  namespace :user do
    resources :reservations, expect: %i[index show]
    resources :clients, expect: %i[index show]
  end

  devise_for :clients
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  scope :rented_false, -> { where(rented: false) }
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :client
  belongs_to :car
  validate :data

  def data
    if date_start < Time.now
      errors[:base] << 'Você não pode selecionar uma data menor que hoje'
    elsif date_end < date_start
      errors[:base] << 'Você não pode selecionar uma data menor que data de inicio'
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard/cars_controller.rb
class Dashboard::CarsController < DashboardController
  before_action :set_cars, only: %i[edit update destroy]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(cars_params.merge(rented: false))
    if @car.save
      redirect_to dashboard_cars_path, notice: "#{@car.model} cadastrado com sucesso!"
    else
      flash.now[:alert] = @car.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @car.update(cars_params)
      redirect_to dashboard_cars_path, notice: "#{@car.model} atualizado com sucesso!"
    else
      flash.now[:alert] = @car.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    if @car.destroy
      redirect_to dashboard_cars_path, notice: "#{@car.model} excluido com sucesso!"
    else
      flash.now[:alert] = @car.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def set_cars
    @car = Car.find(params[:id])
  end

  def cars_params
    params.require(:car).permit(:model, :brand, :board, :model_year, :manufacture_year, :rented)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < DashboardController
  before_action :set_users, only: %i[edit update destroy]
  before_action :allow_without_password, only: [:update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to dashboard_users_path, notice: "#{@user.name} cadastrado com sucesso!"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(users_params)
      redirect_to dashboard_users_path, notice: "#{@user.name} atualizado com sucesso!"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to dashboard_users_path, notice: "#{@user.name} excluido com sucesso!"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_users
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile)
  end

  # remove o input da validação do devise
  def allow_without_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cars = Car.rented_false
  end
end

app/controllers/user/clients_controller.rb
class User::ClientsController < UserController
  before_action :set_clients, only: %i[edit update destroy]
  before_action :allow_without_password, only: [:update]

  def index
    @reservations = Reservation.where(client_id: current_client)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(clients_params)
    if @client.save
      redirect_to user_clients_path, notice: "#{@client.name} cadastrado com sucesso!"
    else
      flash.now[:alert] = @client.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if @client.update(clients_params)
      redirect_to user_clients_path, notice: "#{@client.name} atualizado com sucesso!"
    else
      flash.now[:alert] = @client.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @client.destroy
      redirect_to user_clients_path, notice: "#{@client.name} excluido com sucesso!"
    else
      flash.now[:alert] = @client.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_clients
    @client = Client.find(params[:id])
  end

  def clients_params
    params.require(:client).permit(:name, :email, :password, :password_confirmation, :cpf)
  end

  # remove o input da validação do devise
  def allow_without_password
    if params[:client][:password].blank? && params[:client][:password_confirmation].blank?
      params[:client].delete(:password)
      params[:client].delete(:password_confirmation)
    end
  end
end

app/controllers/user/reservations_controller.rb
class User::ReservationsController < UserController
  before_action :set_reservations, only: %i[edit update destroy]

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservations_params)
    if @reservation.save
      car = Car.where(id: @reservation.car_id)
      car.update(rented: true)
      redirect_to user_clients_path, notice: "#{@reservation.id} feita com sucesso!"
    else
      flash.now[:alert] = @reservation.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update_rented
    @car = Car.update(rented: true)
  end

  def update
    if @reservation.update(reservations_params)
      redirect_to user_clients_path, notice: "#{@reservation.id} atualizada com sucesso!"
    else
      flash.now[:alert] = @reservation.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @reservation.destroy
      car = Car.where(id: @reservation.car_id)
      car.update(rented: false)
      redirect_to user_clients_path, notice: "#{@reservation.id} excluida com sucesso!"
    else
      flash.now[:alert] = @reservation.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_reservations
    @reservation = Reservation.find(params[:id])
  end

  def reservations_params
    params.require(:reservation).permit(:date_start, :date_end, :car_id).merge(client_id: current_client.id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_client!
  layout 'user'

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/cars_helper.rb
module Dashboard::CarsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user/clients_helper.rb
module User::ClientsHelper
end

app/helpers/user/reservations_helper.rb
module User::ReservationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/clients/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/clients/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/dashboard/cars/_form_cars.html.erb
<%= form_with model: [:dashboard, @car], local: true do |f| %>
  <div class="container">
      <div class="row">
        <div class="form-group col-md-3">
          <%= f.label :model %>
          <%= f.text_field :model, class: "form-control" %>
        </div>
        <div class="form-group col-md-3">
          <%= f.label :brand %>
          <%= f.text_field :brand, class: "form-control" %>
        </div>
        <div class="form-group col-md-2">
          <%= f.label :board %>
          <%= f.text_field :board, class: "form-control" %>
        </div>
        <div class="form-group col-md-2">
          <%= f.label :model_year %>
          <%= f.text_field :model_year, class: "form-control" %>
        </div>
        <div class="form-group col-md-2">
          <%= f.label :manufacture_year %>
          <%= f.text_field :manufacture_year, class: "form-control" %>
        </div>

      </div>
    <div class="row mt-3">
      <div class="mx-auto">
        <%= f.submit class: "btn btn-success", data: { disable_with: "Criando....⌛" } %>
        <%= link_to "Cancelar", dashboard_users_path, class: "btn btn-danger ml-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/cars/edit.html.erb
<div class="mt-5">
<%= render "form_cars" %>
</div>

app/views/dashboard/cars/index.html.erb
<h1>Dashboard::Cars#home</h1>
<p>Find me in app/views/dashboard/cars/home.html.erb</p>

app/views/dashboard/cars/new.html.erb
<div class="mt-5">
<%= render "form_cars" %>
</div>

app/views/home/index.html.erb
<div class="container mt-5">
  <div class="row">
    <% @cars.each do |car| %>
      <div class="col-md-4 mb-3">
        <div class="card p-3">
          <%= image_tag("car.jpg", class:"img-fluid p-3") %>
          <p>Modelo: <%= car.model %></p>
          <p>Marca: <%= car.brand %></p>
          <p>Ano: <%= car.model_year %>/<%= car.manufacture_year %></p>
          <%= link_to "Reservar", new_user_reservation_path, class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/shared/dashboard/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'Dashboard', dashboard_users_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Bem Vindo! <%= current_user.name %></span></a>
    </li>
  </ul>
  <form class="form-inline">
    <%= link_to 'Editar Perfil', edit_dashboard_user_path(current_user), class: "btn btn-outline-light my-2 my-sm-0 mr-2" %>
    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-outline-light my-2 my-sm-0" %>
  </form>
</div>
</nav>

app/views/layouts/shared/user/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'Dashboard', user_clients_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Bem Vindo! <%= current_client.name %></a>
      </li>
    </ul>
    <form class="form-inline">
      <%= link_to 'Editar Perfil', edit_user_client_path(current_client), class: "btn btn-outline-light my-2 my-sm-0 mr-2" %>
      <%= link_to "Sair", destroy_client_session_path, method: :delete, class: "btn btn-outline-light my-2 my-sm-0" %>
    </form>
  </div>
</nav>

app/views/user/clients/_form_clients.html.erb
<%= form_with model: [:user, @client], local: true do |f| %>
  <div class="container">
    <div class="row">
      <div class="form-group col-md-3">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :cpf %>
        <%= f.text_field :cpf, class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="mx-auto">
        <%= f.submit class: "btn btn-success", data: { disable_with: "Criando....⌛" } %>
        <%= link_to "Cancelar", user_clients_path, class: "btn btn-danger ml-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/user/clients/edit.html.erb
<div class="mt-5">
  <%= render "form_clients" %>
</div>

app/views/user/clients/index.html.erb
<div class="mt-5 mb-5">
  <%= link_to "<button class='btn btn-success'>Nova Reserva</button>".html_safe, new_user_reservation_path %>
</div>
<h5>Minhas Reservas:</h5>
<div class="row mt-2">
  <% @reservations.each do |reservation| %>
    <div class="col-4">
      <div class="card p-2 mt-2">
        <p>Cód. Reserva: <%= reservation.id %></p>
        <p>Modelo/Marca: <%= reservation.car.model %> / <%= reservation.car.brand %></p>
        <p>Perido Reserva: de <%= reservation.date_start.strftime("%d/%m/%Y") %>
          até <%= reservation.date_end.strftime("%d/%m/%Y") %></p>
        <%= link_to 'Cancelar', user_reservation_path(reservation), method: :delete, data:{ confirm: 'Tem certeza que deseja cancelar?'}, class:'btn btn-danger'%>
      </div>
    </div>
  <% end %>
</div>

app/views/user/clients/new.html.erb
<div class="mt-5">
  <%= render "form_clients" %>
</div>

app/views/user/reservations/_form_clients.html.erb
<%= form_with model: [:user, @reservation], local: true do |f| %>
  <div class="container">
    <div class="row">
      <div class="form-group col-md-4">
        <%= f.label :date_start %>
        <%= f.date_field :date_start, class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :date_end %>
        <%= f.date_field :date_end, class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <label>Carro</label>
        <%= collection_select(:reservation, :car_id, Car.where(rented: false), :id, :model, { prompt: "Selecione" }, { class: "form-control" }) %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="mx-auto">
        <%= f.submit class: "btn btn-success", data: { disable_with: "Criando....⌛" } %>
        <%= link_to "Cancelar", user_clients_path, class: "btn btn-danger ml-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/user/reservations/edit.html.erb
<div class="mt-5">
  <%= render "form_clients" %>
</div>

app/views/user/reservations/new.html.erb
<div class="mt-5">
  <%= render "form_clients" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>